name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (e.g. v1.0.3)"
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download release artifact
        run: |
          gh release download ${{ github.event.inputs.version }} --repo ${{ github.repository }} --pattern "*.jar"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Ensure remote app directory exists
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@3.10.52.0 "mkdir -p /home/ubuntu/app/"

      - name: Deploy to EC2
        run: |
          scp -o StrictHostKeyChecking=no *.jar ubuntu@3.10.52.0:/home/ubuntu/app/
          ssh -o StrictHostKeyChecking=no ubuntu@3.10.52.0 << 'EOF'
            pkill -f 'java -jar' || true
            nohup java -jar /home/ubuntu/app/*.jar > /home/ubuntu/app/output.log 2>&1 &
          EOF
